### ISSUE TITLE
Readonly attribute?

### ISSUE THREAD

**Issue by mootari** [observablehq/inputs#100]
The `Textarea` widget supports the `disabled` attribute, but not `readonly`.

In some instances `readonly` can be more appropriate, e.g. when using a textarea as an output element. In this case it is desirable to render the element as "active", while still preventing edits that would have no effect.

**Comment by mbostock** [comment]
This applies to a number of other potential inputs as well, or at least the Text input.

I’m inclined to not support the readonly attribute because I feel the disabled attribute should be preferred from a usability perspective: a readonly input gives no visible indication that it’s readonly, whereas a disabled input is faded. So a readonly attribute is likely to be surprising and frustrating to the user. If you really just want to show an output value, maybe an output element or similar would be more appropriate?

**Comment by mootari** [comment]
The readonly attribute only applies to inputs which require text entry (text, number, date, email, password). For this library, I believe it's reasonable to limit support to Textarea and Text.

readonly and disabled are not interchangeable:
- A disabled element cannot be focused and displays the default mouse pointer on mouseover.
- A readonly element can be focused, displays the text selection mouse pointer and allows for text selection via the respective select-all shortcut. Its readonly state is indicated by the absence of a text input cursor.
- textarea elements allow for the controlled selection of large amounts of text, and maintain indentation by default.
- An output element by itself has no browser chrome. It is not focusable, and visually indiscernable from other text content.

Accessibility concerns aside (which I still plan to collect and document, both for readonly and disabled), there are real practical applications for readonly.

**Comment by j-f1** [comment]
Here’s an example of a real use case for read-only inputs: https://observablehq.com/@j-f1/sort-lines-of-text?collection=@j-f1/tools
