### ISSUE TITLE
Range doesn't update with non-trivially-fractional step sizes

### ISSUE THREAD

**Issue by rreusser** [observablehq/inputs#120]
## Version

Browser: Chrome 88.0.4324.192
Version: inputs@0.7.17
Platform: Mac OS X 10.13.6

## Expected behavior

Range works as expected given a step size with trailing non-zero digits.

## Observed behavior

Given even a slight deviation from a range evenly divisible by the step size, updates fail to fire, and sometimes dependent cells never exit the initial cell-executing-and-waiting-for-value state.

The image below illustrates normal behavior (top) and problematic behavior (bottom):

https://observablehq.com/d/f23b60cc80002344

![rangebug](https://user-images.githubusercontent.com/572717/110229079-9a70cd00-7ebb-11eb-831d-ac5d73239003.gif)

## Notes:

*Exactly* what it should do is debatable, but maybe `lower + i * step` is a reasonable expectation. I encountered this first with `Range([0, Math.PI], {step: Math.PI / 1000})`, which is a case where you can't really do any better to make it *approximately* evenly divisible.

**Comment by rreusser** [comment]
Edit:

```
viewof y = Range([0, 1.001], { step: 0.01 })
```

 works as expected, so my initial statement that it must be "evenly divisible" is not quite right. It's more like the step size needs to be "nice".

**Comment by jrus** [comment]
I am getting a range that doesn't work at all in Mac Safari with:

```javascript
viewof x = Range([0, 2*Math.PI+1e-15], { step: Math.PI/4 })
```

It never returns a value.

This works more or less as expected though:

```javascript
viewof y = html`<input type=range min=0 max=${2*Math.PI+1e-15} step=${Math.PI/4} value=${Math.PI/2}>`
```

**Comment by jrus** [comment]
I would propose as a workaround using a variable in range [0, 1], [-1, 1], or similar, and then remapping in a wrapper

Maybe something like:

```javascript
viewof x_over_π = Range([0, 2], { step: 0.25, value: 1, format: x => Math.PI * x });
```

```javascript
x = x_over_π * Math.PI
```

**Comment by jrus** [comment]
This may be the same issue as https://github.com/observablehq/inputs/issues/121

**Comment by tophtucker** [comment]
I'm late to the party but just found this issue because a user noted it in the forum: https://talk.observablehq.com/t/set-value-of-range-input/4810

Here's a reproduction showing it breaking in v0.7.13: https://next.observablehq.com/d/e2bbaf2de99c099b

**Comment by tophtucker** [comment]
[Roeland Schoukens reports](https://talk.observablehq.com/t/set-value-of-range-input/4810/6) it was already broken in Windows / Firefox 86 before validation was added in v0.7.13:
>For me (Windows, Firefox 86) both versions on this reproduction don’t work.
>![image](https://user-images.githubusercontent.com/841829/112240234-33664e80-8c05-11eb-8f52-97a0de9dee2d.png)

**Comment by roperzh** [comment]
I believe this is happening because the `value` of the number input can be programmatically changed by functions like `format` (defaults to [`formatDate`](https://github.com/observablehq/inputs/blob/bf525033948bbdda452e65bc06c09a6b42f3b06c/src/format.js#L12-L14))  and `transform`, and they might not return a valid value<sup>[1]</sup>. For example, every time the input range changes, the value of the number range is set like this:

https://github.com/observablehq/inputs/blob/bf525033948bbdda452e65bc06c09a6b42f3b06c/src/range.js#L59-L60

when `update` is called, it calls `HTMLSelectElement.checkValidity()` under the hood, triggering browser validation.

A couple of options that come to mind in no particular order are:

- bypass the browser validation of the number input by setting its `defaultValue` instead of its `value`.
- document that `format` and `transform` must return a valid value<sup>[1]</sup>, and fix `formatDate` accordingly.
- hook into the validation api

[1]: The [HTML living standard](https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#constraints) defines the validations that are performed, for the cases described in this issue the relevant validations could be summarized as: `min < value < max` and `value = n * step`

**Comment by jrus** [comment]
I would consider using custom validation in javascript code instead of relying on the browser's.

**Comment by mbostock** [comment]
The default Range format is derived from formatNumber, not formatDate, and should already be compatible with the number input as noted:

https://github.com/observablehq/inputs/blob/23e6828b4a00835bf5e1b4d5fa13c775b5deaa41/src/range.js#L11

I’m investigating now.

**Comment by mbostock** [comment]
I’ve added a *validate* option to Inputs.number and Inputs.range in 0.9.4.
