### ISSUE TITLE
Color

### ISSUE THREAD

**Issue by mbostock** [observablehq/inputs#42]
You can do Text type = color, but it’d be better with an output element to show the color value.

**Comment by mootari** [comment]
How do you feel about optional transparency support?

**Comment by mbostock** [comment]
@mootari Not sure what you mean. This would use the browser’s native color input, which I don’t think we have control over?

**Comment by mootari** [comment]
I wasn't sure how much you'd want to enhance the default color inputs. Since [support for RRGGBBAA values](https://caniuse.com/css-rrggbbaa) is growing, this might have presented an opportunity to offer a compound color input with optional alpha support.

The [WHATWG discussion](https://github.com/whatwg/html/issues/3400) is still meandering though, so it might indeed be better to stick to the basics, at least for now.

**Comment by triptych** [comment]
👍  https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Input/color
