### ISSUE TITLE
Assigning range.value does not respect the format option.

### ISSUE THREAD

**Issue by severo** [observablehq/inputs#87]
The behavior is different with respect to the precision in Range when two inputs are bound:

https://user-images.githubusercontent.com/1676121/107416970-6650f900-6b15-11eb-9e87-ddf23c427306.mp4

I understand it's because modifying the source sets the target's value, without dispatching the "input" event, while modifying the target sets the source's value and dispatches an "input" event on the source, which in turn updates the target.

**Comment by severo** [comment]
I think there are potentially two problems:
- moving the slide to 15,5955441 and setting the value with `.value=15,5955441` should give the same visual result
- looping (two events) on every interaction with the target might not be something we want. Well, I'm not sure, I understand that the current behavior is: set the value of the source, and let the value flow to its dependencies, here the target. The source must be understood as the source of truth / the store.

**Comment by mbostock** [comment]
This is not a bug with bind, but it is a bug with the Range input. When the range’s value is assigned, we are currently directly setting the number.value:

https://github.com/observablehq/inputs/blob/cc5f9d12f9d6e7ca7849942424b145695bc9de85/src/range.js#L53-L56

We should be respecting the range’s optional *format*, which happens when you drag the slider:

https://github.com/observablehq/inputs/blob/cc5f9d12f9d6e7ca7849942424b145695bc9de85/src/range.js#L42-L44
