### ISSUE TITLE
Wrap Ranges with step: 'any' to use a range of 0–100 internally, so Firefox keyboard control matches other browsers?

### ISSUE THREAD

**Issue by jrus** [observablehq/inputs#92]
In Safari/Chrome, the default keyboard behavior seems to be for the slider to have 100 steps (i.e. each keypress moves the slider by (max-min)/100). In Firefox, the default keyboard behavior is to move by increments of 1 slider unit.

Whether the Firefox behavior should be used for a generic Observable slider is debatable, but this really breaks down completely when working with a scale transformation. For example, a slider from 1–100 on a log scale ends up with log(100) = 4.6 slider-scale units, which means that in Firefox every keypress moves 22% of the full slider range, while each keypress in Chrome or Safari moves 1% of the slider range.

Ideas to consider:

1. override the default firefox behavior to match the behavior in Chrome/Safari
2. give authors some explicit control over keyboard behavior
3. allow modifier + arrows to move in larger or smaller increments than the default

**Comment by jrus** [comment]
No, setting 'step' forces the mouse to snap to those steps

**Comment by mbostock** [comment]
So you just want to change the keyboard behavior? I don’t plan on deviating from the native input behavior here.

**Comment by jrus** [comment]
If the native input were set to internally have a 0–100 range, linearly mapped to whatever other range, then it would be consistent across browsers.

**Comment by jrus** [comment]
(Not sure what happened, but my comment seems to have gotten eaten by Github.)

Here is a concrete example, https://observablehq.com/d/323d5622fbff00b5

One solid workaround that wouldn't require any special keyboard handling code: internally set the slider to use the range 0–100, and then linearly map that to whatever range as part of the internal transformation code. This would make the behavior consistent across browsers.

The current behavior in Firefox makes keyboard adjustment nearly useless for a substantial proportion of Range inputs.

**Comment by jrus** [comment]
I personally would like to keep the default mouse control to have 'any' as the step size.

**Comment by mbostock** [comment]
Safari seems to discourage keyboard input with sliders; clicking on a range input doesn’t focus it, though you can focus it with option tab, and you can use the keyboard on the number input (which then controls the Range). I am going to file a separate issue for the interaction between step and transform; if a (non-identity, non-negate) transform is specified, then we can’t rely on the browser’s implementation of step, and we should either ignore the step entirely on the range input or we should implement the step in JavaScript. But I’m going to close this issue because I don’t plan on taking any steps to address keyboard control on Firefox.
